### ISSUE TITLE
Text file text is obscured by the scrollbar

### ISSUE THREAD

**Issue by superjer2000** [ksherlock/gopher#3]
Text that spans the entire window is covered by the scrollbar (i.e. the scrollbar cuts off the text on the right hand side of the window.)  (Both with word wrap on and off).

ROM01 IIgs.

Great Gopher client!!

**Comment by ksherlock** [comment]
https://github.com/ksherlock/gs-gopher is the GUI one 😄 

Anyhow, looks like you're right.  I set the text edit word wrap flag and that kind of works but now I think I need to adjust the ruler right margin as well.

**Comment by ksherlock** [comment]
This has been fixed.  https://github.com/ksherlock/gs-gopher/releases/tag/alpha-4
